/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import WidgetMgr from "./HMFW/WidgetMgr"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1080;
    static height:number=1920;
    static scaleMode:string="fixedauto";
    static screenMode:string="none";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="PhotoAlbumUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("HMFW/WidgetMgr.js",WidgetMgr);
    }
}
GameConfig.init();